- name: create topics
  command: /opt/kafka/bin/kafka-topics.sh --zookeeper {{processing_zookeeper_ip}}:2181 --create --topic {{env}}.{{item.name}} --partitions {{ item.num_of_partitions }} --replication-factor {{ item.replication_factor }}
  with_items: "{{processing_lern_kafka_topics}}"
  ignore_errors: true
  when: kafka_id=="1"
  tags:
    - processing-kafka

- name: override retention time
  command: /opt/kafka/bin/kafka-topics.sh --zookeeper {{processing_zookeeper_ip}}:2181 --alter --topic {{env}}.{{item.name}} --config retention.ms={{ item.retention_time }}
  with_items: "{{processing_lern_kafka_overriden_topics}}"
  when: kafka_id=="1" and item.retention_time is defined
  tags:
    - processing-kafka

- name: overriding lern data pipeline downstream topic size
  shell: "/opt/kafka/bin/kafka-topics.sh  --zookeeper {{processing_zookeeper_ip}}:2181 --alter --topic {{item}} --config max.message.bytes={{dp_downstream_kafka_max_message_bytes}}"
  with_items:
    - "{{env}}.telemetry.raw"
